### PR TITLE
common-service-play: db2u operator install alongside ics

### PR DESCRIPTION
**Pull request by afzalch**
Provides user the option of installing db2u operator while installing common-services. This is a new feature that has been added with ICS 3.7.1. I tested this branch in my code and was able to successfully get CS 3.7.1 and db2u operator installed as you can see with the image below

image

This PR is related to this open issue https://github.com/IBM/community-automation/issues/128

### CODE REVIEW

**Comment by rayashworth** [comment]
@afzalch @ratripathi  would it have mades sense to create a new role, and just include the role in common services, instead of adding a task to common services directly.

**Comment by rayashworth** [comment]
@afzalch I have others reviewing this as well.  We may need to discuss details next week.

**Comment by websterc87** [comment]
I would recommend us moving this valuable code to its own role. That way we can avoid duplicating most of the install.yml.

This role could just include the single step that does `oc apply -f db2-catalog-source.yaml`
with the template and the variable. 

@afzalch Was there a particularly reason for putting in the same role. e.g. Does the DB2 Operator depend on common services? if so we can achieve the same result a different way. If you want help or advise on how to move the code I am happy to help.

**Comment by rayashworth** [comment]
@afzalch please join Mondays webex at 10am ET.  https://ibm.webex.com/meet/ashworth

This would be a great topic.

**Comment by afzalch** [comment]
Sure, I can join the webex on Monday. 

@websterc87 I just added it to this particular role because it seemed the easiest and most straight forward approach to me as someone who was attempting to make a quick and easy change. If we want to create a new role for this scenario, that totally makes sense to me in terms of code maintainability and readability, so I can work on implementing that later today and show it in the Monday webex meeting.

**Comment by rayashworth** [comment]
@afzalch Sounds good, thanks!

**Comment by afzalch** [comment]
Thanks to some help by @ratripathi I was able to get Db2 operator installed after common service using the `db2-openshift-play` playbook. Thanks for all the help and for inviting me to webex today @rayashworth to work out the bugs and plan my approach.

**Pull request closed without merging**
