### PR TITLE
add ssh_key to defaults and update related files

### PR DESCRIPTION
**Pull request by rayashworth**
Not quota to tests, but would like this reviewed.

### CODE REVIEW

**Comment by rayashworth** [comment]
PR was updated to change the variable from ssh_key to ssh_key_file to remove confusion on file vs real value.

**Review by websterc87 — APPROVED** [review]
Minor change to public key would be more intuitive other change looks good

**Comment by rayashworth** [comment]
change to more specific value for the variable.  **ssh_public_key_file**

**Review by websterc87 — APPROVED** [review]
Looks good

**Review by wkrapohl — COMMENTED** [review]
lgtm

**Pull request merged**
